# Generated by Django 5.1.6 on 2025-04-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0005_interest_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='topic',
        ),
        migrations.AddField(
            model_name='interest',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='interest',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
