# Generated by Django 5.1.6 on 2025-04-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0007_interestcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_user.interestcategory'),
        ),
    ]
