# Generated by Django 5.1.6 on 2025-04-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0008_alter_interest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Unnamed Event', max_length=255),
        ),
    ]
