# Generated by Django 5.1.6 on 2025-04-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0009_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='season',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='travel_type',
            field=models.CharField(max_length=50),
        ),
    ]
