# Generated by Django 5.1.6 on 2025-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0011_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(),
        ),
    ]
