# Generated by Django 5.2 on 2025-04-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0013_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
