# Generated by Django 5.2 on 2025-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0014_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='travel_type',
        ),
        migrations.AddField(
            model_name='location',
            name='activities',
            field=models.TextField(default='No activities available'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default='location.jpg', upload_to='locations/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=50),
        ),
    ]
