# Generated by Django 5.2 on 2025-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0015_remove_location_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='locations/')),
                ('activities', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(upload_to='locations/'),
        ),
    ]
